term xterm-kitty

shell zsh

font_family 	JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_shape beam

disable_ligatures never

font_size 15.0

enable_audio_bell no

enabled_layouts splits:split_axis=horizontal

include nord.conf
